### ISSUE TITLE
Sync Error 

### ISSUE THREAD

**Issue by danwiz85** [UniversalDevicesInc/UD-Mobile-Android#10]
FINISHED WITH ERROR

Error(IOException)java.io.IOException: Unexpected end of stream on com.android.okhttp.address@2d9fdaad

Error getting Network Resources.  
Disregard id non exist. Error: 404

**Comment by JavierRefuerzo** [comment]
Hi @danwiz85,

If you do not have Network Resources we can disregard the second error.

Will look into the second error and try to add more detail.  Does this happen every time sync is performed?

**Comment by danwiz85** [comment]
No network resources.

Sync error happens all the time.

Dan

**Comment by JavierRefuerzo** [comment]
Hi @danwiz85 ,

Does this issue persist as of version 0.34?

**Comment by JavierRefuerzo** [comment]
Closing as no response
