### ISSUE TITLE
Unable to Connect Remotely

### ISSUE THREAD

**Issue by danwiz85** [UniversalDevicesInc/UD-Mobile-Android#11]
I can connect local, but remote get error:

Error: Error(IOException)
javax.net.ssl.SSLHandshakeException:Java.security.cert.CertPathValidationException: Trust anchor for certification path not found.

**Comment by JavierRefuerzo** [comment]
Hi @danwiz85,
Thanks for testing.  

Based on the error it looks as if your are not using the ISY Portal, Is this correct?
If not using the portal, currently, the app only supports remote connections using A) VPN and selecting "Only Use Local Connection" or B) A valid CERT.   Apple and Google have given developers notice that bypassing security may result in removal from the app stores. While it is currently possible to bypass the https CERT there is no guarantee it will work on the next version or that it will not result in removal from the respective app platforms.

**Comment by danwiz85** [comment]
You are correct, I'm using mobilinc because you don't have a mobile app.

Okay, I'll create a cert in the next day or two.

**Comment by JavierRefuerzo** [comment]
Thanks.  

Please note this will not work with self signed CERTs unless trusted by the Android System.  Adding a self signed CERT to the Android system is beyond the scope of support for this app.

**Comment by danwiz85** [comment]
Okay.
