### ISSUE TITLE
FInished with Error

### ISSUE THREAD

**Issue by Damyers6937** [UniversalDevicesInc/UD-Mobile-Android#12]
When doing a sync, I get this error, have not figured out which node is causing it yet.  Everything seems to be working good so far even with this error.  
The interface I like better than mobillinc in general, they do have a nicer thermostat screen. Over all so far this working much better.

![Screenshot_20201130-102142 (2)](https://user-images.githubusercontent.com/75264113/100629443-4b812d80-32f7-11eb-9963-b4bf75c0cc9c.png)

**Comment by JavierRefuerzo** [comment]
Hi @Damyers6937 ,
Thanks for testing.
I have added an instance to the error message so we can track down the node server causing the issue.  Most likely improperly formatted XML.  The ISY may accept these without errors however most parsers in Android and iOS will throw.
Will be in version 0.29, please let me know of the offending node server so we can notify the dev.

**Comment by JavierRefuerzo** [comment]
Hi @Damyers6937 ,

Does this issue persist as of version 0.34?

**Comment by JavierRefuerzo** [comment]
Closing as no response
