### ISSUE TITLE
Good Stuff!!!

### ISSUE THREAD

**Issue by glenncs** [UniversalDevicesInc/UD-Mobile-Android#14]
Only positive stuff with this post:
* Side loaded it on a Fire 10 tablet (latest model).  It works!!!
* Connected to two different ISYs.  It works!
* Not much time spent on it, but everything seems self explanatory and what I have tried works!
There was one lockup, I believe after I had added the second ISY node.  Killed the app and the 2nd node was there and working when I started the app again.
Mobilinc has done so little in adding to their app other than trying to charge so much more.  Thanks for making this happen!

I am mostly an iPhone person and am looking forward to an iPhone version.  However, I know you have to start somewhere and I agree that Android was the right choice.
Thanks!!

**Comment by mkohanim** [comment]
Thank YOU!

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************
