### ISSUE TITLE
Scenes do not behave intuitively

### ISSUE THREAD

**Issue by jfai** [UniversalDevicesInc/UD-Mobile-Android#2]
Sample scene with multiple Insteon responders. 

Some responders are configured "off" and some are configured "on".
When I click "on" or "fast on" for the scene, all devices are turned "on".

I expected for the scene to be in "on" state, i.e., some devices should be "on" and some devices should be "off".  

Maybe there should be a separate button for "run scene".

The current implementation for scenes functions the same as the Ajax implementation.

**Comment by JavierRefuerzo** [comment]
Hi @jfai ,
I ran some tests and cannot reproduce the issue.  
Currently setting On Level is only supported in Admin Console, So for testing changed On Level Values there. 
When I change the On Level for an Insteon Switch to "off" and press "on"  from the scene in the app the light will remain off. If changed to a % value it will go to that value.

Can you please recheck this, or have I misunderstood the Issue?
Thanks

**Comment by jfai** [comment]
It turned out to be a synchronization issue between the Insteon switch settings and the ISY. The on-levels in the ISY scene definition for the responders that were supposed to be "Off" were actually "100%". The controller (a keypad toggle button) was still doing the right thing. However, clicking on "On" in the admin console or the UD Mobile app was setting the levels according to what the ISY settings were.

Since the keypad button was executing the scene as expected, I didn't check the settings in the ISY. I don't know which of the updates of the ISY firmware messed up the scene settings.

After fixing the ISY scene settings, UD Mobile now runs the scene as expected (as does the admin console).

**Comment by JavierRefuerzo** [comment]
Great!
