### ISSUE TITLE
"Editor Object is null" for energy-monitoring zwave plugs

### ISSUE THREAD

**Issue by DaveStLou** [UniversalDevicesInc/UD-Mobile-Android#27]
I have several generic energy-monitoring zwave plugs. When I attempt to create functions based on the energy node, I get an error "Editor Object is null. Synchronization may be required. 500". I've tried resyncing several times but same error occurs. I've attached screenshot.

Below is the information from one of the plugs as dumped by ISY 994i:
Coffeemaker Outlet Z77
ZW077_1 uid=77 security=None type=4.16.1 mid=600 tid=3 pid=135
Association Group ID 1
    -  x5E  V2   ZWAVEPLUS_INFO
    -  x72  V2   MANUFACTURER_SPECIFIC
    -  x86  V2   VERSION
    -  x85  V2   ASSOCIATION
    -  x59  V1   ASSOCIATION_GROUP_INFO
    -  x5A  V1   DEVICE_RESET_LOCALLY
    -  x73  V1   POWERLEVEL
    -  x70  V1   CONFIGURATION
    -  x25  V1   SWITCH_BINARY
    -  x27  V1   SWITCH_ALL
    -  x71  V8   NOTIFICATION
    -  x32  V4   METER
    -  x20  V1   BASIC
 - Secure
 
![UDMobileError](https://user-images.githubusercontent.com/16002402/146022594-27f5781c-b04b-4a0d-9cbf-7173e63bed8a.png)

**Comment by JavierRefuerzo** [comment]
Hi @DaveStLou ,

Can you please send me a copy of the backup along with the address of one of the nodes with the issue.  Please send via email or forum PM.  javier at universal-devices dot com

**Comment by DaveStLou** [comment]
Sent via forum PM.

**Comment by JavierRefuerzo** [comment]
Commit # d19c0c8.  Added encoded editor parsing and insertion for Node Def Status Editors.  Included in version 0.117

**Comment by DaveStLou** [comment]
Has 0.117 been uploaded to Google Play store? It's showing 0.116 as current version.

**Comment by JavierRefuerzo** [comment]
Not yet, I had to wait for 0.116 to go live. So, hopefully it should be live by sometime tomorrow.
