### ISSUE TITLE
could not sync.. log filled with timeouts and "please notify developer"

### ISSUE THREAD

**Issue by nlaredo** [UniversalDevicesInc/UD-Mobile-Android#4]
![image](https://user-images.githubusercontent.com/9362126/100554672-08698080-324b-11eb-965d-7deaa37780a9.png)
system version 5.3.0, all device nodes should be insteon

**Comment by JavierRefuerzo** [comment]
Hi @nlaredo ,
Thanks for testing. Version 0.26 was pushed with longer timeout. Please update if issue is fixed or is persistent.
If error persists please report with version number.
Thanks!

**Comment by nlaredo** [comment]
With the new version I am now able to control my insteon devices...but startup sync was not without errors:

![image](https://user-images.githubusercontent.com/9362126/100568133-27820580-327f-11eb-9c74-48eb1cd424c1.png)

it spends a long time on zwave (I have no zwave devices).  For what it's worth, regarding timeout assumptions... my ping time to your amazon ec2 instance for my.isy.io is approximately 75ms whereas ping time for google.com is approximately 8ms.

**Comment by JavierRefuerzo** [comment]
Thanks, this is of much help.  It appears most of these issues do come from Systems w/o Z-wave.  We are looking into the issue and hope to have a fix soon.

Thanks for your detailed report!
Javier

**Comment by JavierRefuerzo** [comment]
Hi, found an issue with feature verification, Z-Wave being a feature.  I'm not sure if this will fix your issue but it may narrow some of the errors. Version 0.27

**Comment by JavierRefuerzo** [comment]
Hi @nlaredo ,

Does this issue persist as of version 0.34?

**Comment by JavierRefuerzo** [comment]
Closing as no response

**Comment by nlaredo** [comment]
> Closing as no response

I can confirm that it works without any errors other than the state variables not existing (don't have any).. as long as I don't have a local network selected.
