### ISSUE TITLE
Typo in eisy wifi configuration

### ISSUE THREAD

**Issue by cprail1** [UniversalDevicesInc/UD-Mobile-Android#41]
Javi, 

Minor typo in an eisy wifi set up error screen to which I managed to find my way .    "bo" instead of "to"  . 
![Screenshot_20221231-134203](https://user-images.githubusercontent.com/52812145/210158513-309cd204-ace7-436d-a4a7-51d4624ed276.png)

**Comment by JavierRefuerzo** [comment]
Thanks for the report. Fixed typos in 1.0.13
