### ISSUE TITLE
On local test Error 404 nodeServerFileObjects array is null for family enum: -1 Please notify developer same error family enum: 10, family enum: 4, family enum 1

### ISSUE THREAD

**Issue by nadler1ny** [UniversalDevicesInc/UD-Mobile-Android#5]

**Comment by JavierRefuerzo** [comment]
Hi @nadler1ny,
Thanks for testing.
A version 0.26  was pushed in an attempt to fix timeout issues. Please resync when available. If problem persists please share screen shot and version number.
Thanks!

**Comment by JavierRefuerzo** [comment]
Hi @nadler1ny ,

Does this issue persist as of version 0.34?

**Comment by JavierRefuerzo** [comment]
Closing as no response
