### ISSUE TITLE
Could not sync, looking for z-wave array

### ISSUE THREAD

**Issue by Rcmanaka** [UniversalDevicesInc/UD-Mobile-Android#6]
Unable to sync with multiple time out errors and failed loading z-wave array (but I don't have the z-wave module installed on this ISY. 
![Screenshot_20201129-154228](https://user-images.githubusercontent.com/75228070/100557481-7e83dc80-3277-11eb-9063-4178f7eae792.png)

**Comment by JavierRefuerzo** [comment]
Hi @Rcmanaka,
Thanks for testing. Version 0.26 was pushed with longer timeout. Please update if issue is fixed or is persistent.
If error persists please report with version number.
Thanks!

**Comment by JavierRefuerzo** [comment]
Hi, found an issue with feature verification, Z-Wave being on of these.  I'm not sure if this will fix your issue but it may narrow some of the errors.  Version 0.27

**Comment by Rcmanaka** [comment]
FANTASTIC! version 0.27 solved my synchronization issues and the app seem to be working correctly (at least for my simple "Philly" instance.  Thanks for your amazing work!

![Screenshot_20201130-101932](https://user-images.githubusercontent.com/75228070/100628666-76b74d00-32f6-11eb-9371-8b424af8129a.png)
![Screenshot_20201130-101953](https://user-images.githubusercontent.com/75228070/100628667-76b74d00-32f6-11eb-854c-2885b587f9f8.png)
![Screenshot_20201130-102017](https://user-images.githubusercontent.com/75228070/100628669-76b74d00-32f6-11eb-852d-d09f642003c4.png)

**Comment by Rcmanaka** [comment]
I have a much more complex instance in California which includes Z-Wave integration, but since I can only install/maintain remotely at the moment I think I will wait just a bit...

**Comment by JavierRefuerzo** [comment]
Great!

Are you using the ISY Portal for remote connection? If you are the app should sync,  No data in the ISY or Portal is changed by using the app aside from using one of the many subscriptions, only while the app is in use.

**Comment by Rcmanaka** [comment]
YES!  It’s a fantastic combo!

Many thanks!

Randall
