### ISSUE TITLE
Finished with Error! No devices, no variables, no networking resources. 

### ISSUE THREAD

**Issue by Dr-DsK** [UniversalDevicesInc/UD-Mobile-Android#7]
![20201129_230708](https://user-images.githubusercontent.com/75229761/100567918-b26efa00-3297-11eb-93f4-4d1d962b23e9.jpg)

**Comment by JavierRefuerzo** [comment]
Hi @Dr-DsK,
Thanks for testing. Version 0.26 was pushed with longer timeout. Please update if issue is fixed or is persistent.
If error persists please report with version number.
Thanks!

**Comment by Dr-DsK** [comment]
Moved to ver 0.26 and loaded with no errors. And can see all my devices and programs and variables.
But now upon reopening app I get the following error:

    UD Subscription Status - ERROR
    All Systems are disabled in System Settings Restarting attempt number: 0

The error then disappears and the app seems to work. I can control devices. When I leave screen the error sometimes reappears

**Comment by JavierRefuerzo** [comment]
Thanks, Will look into the notification.

**Comment by Dr-DsK** [comment]
Point of information: The error occurred when connected locally (via WiFi). It does not seem to occur when remotely connected

**Comment by JavierRefuerzo** [comment]
Thanks,
I was able to reproduce the error if a system is disabled on the first save as it produces a conflict of notification type by ID.

When the app is started however it should say "Attempting Connection".  This initial notification should only last until the first ISY is connected to the system at which point each ISY will get its own notification to show status/retries.  This should also not pop out.  This fix may take a few days. Will update when ready.

**Comment by JavierRefuerzo** [comment]
Hi @Dr-DsK ,

Does this issue persist as of version 0.34?

**Comment by Dr-DsK** [comment]
The problem is resolved. Sorry for not closing it out.

**Comment by JavierRefuerzo** [comment]
Thanks!
