### ISSUE TITLE
Unable to setup new UD - Android release

### ISSUE THREAD

**Issue by Travgiala** [UniversalDevicesInc/UD-Mobile-Android#8]
First error was URL Null
Now the error states invalid credentials 401

**Comment by JavierRefuerzo** [comment]
Hi @Travgiala ,
Thanks for reporting.  Is this on the Remote Connection or Local Connection? 
Please do post a screenshot or error message shown when "Test System" is pressed.

**Comment by Travgiala** [comment]
I get the error just trying to save my setup data.

**Comment by Travgiala** [comment]
I get the error message when saving the setup data.

**Comment by JavierRefuerzo** [comment]
Hi,
Is this for Remote Connection, ISY Portal, or local connection?
What is the UD Mobile Version Number (Settings>About)?
Please provide error listed when pressing "Test System on Remote URL.
Thanks

**Comment by Travgiala** [comment]
I've tried both remote and local. I get a same error message?

**Comment by Travgiala** [comment]
Version 0.26

**Comment by JavierRefuerzo** [comment]
Invalid Credentials 401 is username or password are incorrect.

I could not find a reference to "URL null". There are a few references to "URL is null".  
I was able to reproduce the "URL is null" when only "http://" or "https:// " are entered as the address. Is the full address entered correctly?  Was the search function used?  

Please note that I have encountered issues there the local search could not find the ISY,  this is usually resolved if the android device is restarted.

**Comment by Travgiala** [comment]
Believe I have the issue resolved!

**Comment by JavierRefuerzo** [comment]
Great!
