### ISSUE TITLE
Enabling local network connection causes commands to change to "DON" "DOFF" "FDUP" etc... and all commands return ERROR: Error: Error: 404

### ISSUE THREAD

**Issue by nlaredo** [UniversalDevicesInc/UD-Mobile-Android#9]

**Comment by JavierRefuerzo** [comment]
Hi @nlaredo,

Does this happen on both local and remote?   I think this is related to the sync issues for family 1 (insteon), as the files which contain the command names do not appear to be downloaded. Please do let me know so issues can be merged.

Thanks for reporting!

**Comment by nlaredo** [comment]
only when local is enabled in the config.  Remote shows the right things and allows me to interact properly.  This is an insteon-only system.

**Comment by JavierRefuerzo** [comment]
Thanks, 

If the local and remote connections are setup as the same system the same database values are used, so I do have a few questions.  Most of the 400 error codes would be invalid credentials.

Do you have local and remote setup as the same system?  When in the System settings is there an error when pressing "Test System On Local Network" on the bottom of "Local Connection Settings"?

**Comment by JavierRefuerzo** [comment]
Hi @nlaredo ,

Does this issue persist as of version 0.34?

**Comment by JavierRefuerzo** [comment]
Closing as no response

**Comment by nlaredo** [comment]
The problem persists:
![image](https://user-images.githubusercontent.com/9362126/102525604-581fb880-404f-11eb-83ac-ac7c11f3e8e0.png)

**Comment by nlaredo** [comment]
In summary, I still cannot control devices if the local network is enabled.  I have to disable the local network for it to work.

The devices appear, but their controls are unusable.

**Comment by JavierRefuerzo** [comment]
Hi @nlaredo ,
Thanks for the feedback.  This is very odd, as (A) the files requests on local or remote networks have the same endpoint, and (B) some of the local request are being fulfilled (rest/time, rest/config, rest/nodes, rest/vars/x) as they do not show an error.  

If it's not too much to ask, please send me the response when you execute the rest request, at the bottom of this comment, from a browser on the local network, where <ip-address> is replaced with the ip address of the ISY?

If synced from remote then local is enabled, without sync on local (select cancel when saved), do local network controls work?  I ask as, if it does not work, then it appears the ISY does not like the local network creds in just some of the rest requests.

Thank you!

http://<ip-address>/rest/profiles/family/-1/files

**Comment by nlaredo** [comment]
<?xml version="1.0" encoding="UTF-8"?><profiles><profile family="-1" id="1"><files dir="NLS"><file name="EN_US.TXT" /></files><files dir="EDITOR"></files><files dir="NODEDEF"></files><files dir="LINKDEF"></files></profile></profiles>

**Comment by cprail1** [comment]
Javi,

This same thing happened to me last night and I do NOT have any local connections set up. I did a sync at about 11 pm and a) it took a very long time - say 5 minutes  and b) when it was complete I had these same commands replacing what had been the expected choices. I synched twice and the exact same thing happened.

My only new point to this thread is that I've no local connections set up but did experience it on a previously working install.

A resynch this morning (~11:10 am pst) took the expected amount of time and resolved the issue.

In case it helps, Peter

**Comment by JavierRefuerzo** [comment]
Hi @cprail1 ,

Thanks.  It is expected if the sync fails there will be issues. If the app can not obtain the family-files it will get raw values for the devices. Network issues between the Android device, ISY portal, and ISY is expected.  As noted, most network issues should resolved with time.

@nlaredo 
Thank you.
We are investigating the issue.  Can you confirm your ISY firmware version?   Does this persist after a reboot of the ISY?

**Comment by nlaredo** [comment]
ISY
Model: ISY 994i 1024 IR
Platform: ISY-C-994
Version: 5.3.0
Build Timestamp: 2020-10-01-14:44:54

**Comment by JavierRefuerzo** [comment]
Hi @nlaredo ,

Version 0.35
Sorry for the long process.  I have added additional logging to the sync to verify the app is requesting the correct url.  Please post a screenshot of the sync error when you get a chance. 

Thank you.

**Comment by nlaredo** [comment]
sorry for the delay from the holidays.. there are still issues with 0.35 when local network connection is used:

![image](https://user-images.githubusercontent.com/9362126/103950199-564a9180-50f1-11eb-94e8-59914f3dcc79.png)
![image](https://user-images.githubusercontent.com/9362126/103950236-62365380-50f1-11eb-83af-763566978dee.png)

**Comment by JavierRefuerzo** [comment]
Hi @nlaredo ,

Thank you.  What IP Address are you using?  I can reproduce this error if there is an extra "/" at the end of the IP address.

**Comment by nlaredo** [comment]
You are correct.  Removing the trailing / in the ip address field fixes it and I am able to control devices.  The ip address field was filled out initially as http://ipaddr/  where the ipaddr was the current ip address that I found in my router for the isy.   In my windows 10 web browser http://isy/ worked by itself to access http://192.168.68.97/WEB/udajax.htm, but on my mac, i need the ip address specifically, and it appears that way for this app as well, so I had typed it in as http://192.168.68.97/ in the field of the app having cut & pasted it from chrome on my phone after verifying that it was still the current ip address.

**Comment by JavierRefuerzo** [comment]
Great!

**Comment by nlaredo** [comment]
please keep in mind that the software principle of "be liberal in what you accept" is being violated by breaking everything with a trailing slash.  I hope future releases are more liberal in what they accept.

**Comment by JavierRefuerzo** [comment]
Hi @nlaredo ,

Thank you for your time in helping us resolve this issue. We do and will continue to accept and correct as many errors as possible.  From your example we observed that our tests accepted the error and the sync did not.  However, the ISY has the ability to accept may types of connections. So, filtering addresses which may be redirects,  may cause errors for other users. 

To help us with future development; may I ask why the search button was not used?

**Comment by nlaredo** [comment]
The search button was not obvious enough to realize what it did. If it said
literal words instead like "find ip" I might have noticed it existed before
you mentioned it. I tried it just now and it did find the ip. I have a
vague memory of trying it in the first version released and it found
nothing but that may be because my home network is larger than a /24.
